sudo: false
language: node_js
cache:
  directories:
    - node_modules
script:
  - cd demo
  - npm install
  - ng build --prod --base-href "https://greentube.github.io/ngx-modal/"
  - ngh --no-silent --repo=https://GH_TOKEN@github.com/greentube/ngx-modal.git --name="meeroslav" --email=meeroslav@yahoo.com

notifications:
  email: false
node_js:
  - '5'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^3
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
