sudo: false
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm i --silent --no-optional -g @angular/cli@1.5.4
  - npm i --silent --no-optional -g angular-cli-ghpages@0.5.2

notifications:
  email: false
node_js:
  - '5'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^3
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
